# Reading from a file

https://pythonspot.com/en/read-file/

In [1]:
import os.path

# Define a filename.
filename = "testing.txt"

if not os.path.isfile(filename):
    print 'File does not exist.'
else:
    # Open the file as f. 
    # The function readlines() reads the file.
    with open(filename) as f:
        content = f.read().splitlines()
        
    # Show the file contents line by line.
    # We added the comma to print single newlines and not double newlines.
    # This is because the lines contain the newline character '\n'. 
    for line in content:
        print(line)

This a test!

How do you know if it passed?
You are reading everything currently in the file

Good Bye!

+ ### read()

In [2]:
#return one big string
filename = "testing.txt"
f = open(filename, "r")
print f.read()

This a test!

How do you know if it passed?
You are reading everything currently in the file

Good Bye!

+ ### readline()

In [3]:
#readline	#return one line at a time
filename = "testing.txt"
f = open(filename, "r")
print f.readline()

This a test!

+ ### readlines()

In [4]:
#returns a list of lines
filename = "testing.txt"
f = open(filename, "r")
print f.readlines()

['This a test!\n', '\n', 'How do you know if it passed?\n', 'You are reading everything currently in the file\n', '\n', 'Good Bye!']

# Writing on a File

In [5]:
# Filename to write
filename = "newfile.txt"


# Open the file with writing permission
myfile = open(filename, 'w') # 'w':creates a new file (or overwrites) with the data.

# Write a line to the file
myfile.write('Written with Python\n')

# Close the file
myfile.close()

## Flag Actions

### Append a File

+ ##### 'a' add content to the file
+ ##### 'r'  Open file for reading 
+ ##### 'w'  Open file for writing (will truncate file) 
+ ##### 'b'  binary more 
+ ##### 'r+' open file for reading and writing 
+ ##### 'a+' open file for reading and writing (appends to end) 
+ ##### 'w+' open file for reading and writing (truncates files)

## Reading Data Files

https://www.analyticsvidhya.com/blog/2016/01/complete-tutorial-learn-data-science-python-scratch-2/

In [6]:
import pandas as pd
df = pd.read_csv("dataTrain.csv") #Reading the dataset in a dataframe using Pandas

+ ### Quick Data Exploration

have a look at few top rows by using the function head()

In [7]:
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

+ ### Summary of numerical fields 

using describe() function

describe() function would provide count, mean, standard deviation (std), min, quartiles and max in its outpu

In [8]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

# Reading from the web

In [9]:
import urllib

link = "http://csc.villanova.edu/aboutUs/mission"
f = urllib.urlopen(link)
myfile = f.read()
print myfile

<!DOCTYPE html>
<html>
	<head>

		<!-- url_for fixes when a sub page attempts to inherit css/js -->
			<link rel="stylesheet" type="text/css" href="/static/css/style.css">
			<link rel="stylesheet" type="text/css" href="/static/bower_components/ionicons/css/ionicons.min.css">
			<script src="/static/js/jquery-2.1.1.min.js"></script>
			<meta charset=utf-8 />
		    <meta name="viewport" content="width=device-width" />
			<title>
			 	Computer Science Department
			</title>

	</head>
	<body>
		<div id="header">

				<div id="banner"><div id="banner-content">
	<a href="/" id="logo-link"><img id="logo" src="/static/images/logo-white-binary-2.png" alt="Logo"/></a>
	<div id="header-text"><span>Department of Computing Sciences</span></div>
	<div id="header-text-responsive">Department of CS</div>
</div></div>
				<div id="nav-wrapper">
  <link rel="stylesheet" type="text/css" href="/static/css/navigation.css">
  <script src="/static/js/jquery-2.1.1.min.js"></script>


<div id="nav-switch"><i class="icon ion-navicon-round"></i></div>

<ul id="nav">

  <li class="nav-item">
    <a href="/aboutUs">About Us</a>
    <ul class="subnav">
      <li class="subnav-item"><a href="/aboutUs">General Information</a></li>
      <li class="subnav-item"><a href="/aboutUs/mission">Mission and Goals</a></li>
      <li class="subnav-item"><a href="/aboutUs/facStaff">Faculty and Staff</a></li>
      <li class="subnav-item"><a href="/aboutUs/prospective">Prospective Students</a></li>
      <li class="subnav-item"><a href="/research/soon">Images</a></li>
    </ul>
  </li>

  <li class="nav-item">
    <a href="/academics">Academics</a>
    <ul class="subnav">
      <li class="subnav-item"><a href="/academics">Overview</a></li>
      <li class="subnav-item"><a href="/academics/undergraduate">Undergraduate</a></li>
      <li class="subnav-item"><a href="/academics/graduate">Graduate</a></li>
      <li class="subnav-item"><a href="/academics/bsms">BS/MS 5-Year</a></li>
      <li class="subnav-item"><a href="/academics/other">Other Programs</a></li>
      <li class="subnav-item"><a href="/academics/courses">Course Information</a></li>
      <li class="subnav-item"><a href="/support">Support</a></li>
      <li class="subnav-item"><a href="/academics/academicIntegrity">Academic Integrity</a></li>
    </ul>
  </li>

  <li class="nav-item">
    <a href="/research">Research</a>
    <ul class="subnav">
      <li class="subnav-item"><a href="/research">Overview</a></li>
      <li class="subnav-item"><a href="/research/interests">Faculty Interests</a></li>
      <li class="subnav-item"><a href="/research/soon">Graduate IS Topics</a></li>
      <li class="subnav-item"><a href="/research/undergradresearch">Undergrad Research</a></li>
      <li class="subnav-item"><a href="/research/technicalreports">Technical Reports</a></li>
      <li class="subnav-item"><a href="http://ceet.villanova.edu">CEET</a></li>
      <li class="subnav-item"><a href="http://www1.villanova.edu/villanova/artsci/ceet/cave.html">The Cave</a></li>
    </ul>
  </li>

  <li class="nav-item">
    <a href="/opportunities">Opportunities</a>
    <ul class="subnav">
      <li class="subnav-item"><a href='/opportunities'>Overview</a></li>
      <li class="subnav-item"><a href='/opportunities/activities'>Student Activities</a></li>
      <li class="subnav-item"><a href='/opportunities/vics'>VICS Scholarships</a></li>
      <li class="subnav-item"><a href='/opportunities/vatican'>The Vatican Internship</a></li>
      <li class="subnav-item"><a href='/opportunities/gradasst'>Graduate Assistants</a></li>
      <li class="subnav-item"><a href='/opportunities/other'>Other Jobs/Internships</a></li>
    </ul>
  </li>

  <li class="nav-item">
    <a href="/news">News and Events</a>
    <ul class="subnav">
      <li class="subnav-item"><a href='/news'>News</a></li>
      <li class="subnav-item"><a href='/news/Colloquia'>Colloquia</a></li>
      <li class="subnav-item"><a href='/news/soon'>Alerts</a></li>
      <li class="subnav-item"><a href='/news/soon'>Newsletter Archive</a></li>
      <li class="subnav-item"><a href="https://go.activecalendar.com/Villanova">Campus Events</a></li>
    </ul>
  </li>
</ul>


<script type="text/javascript" src="/static/js/navigation.js"></script>
</div>
				<div id="loginbar"><div id="loginbar">

	<form method="get" action="/login">
    	<button type="submit" id="ne-edit" title="edit">
    		<span><i class="icon ion-log-in"></i>&nbsp&nbspLogin</span></button>
	</form>

</div></div>

		</div>

		<div id="page-content">
			<div id="content-wrapper">
    <div id="content">
    	<div id="overview">
		<div id="mission">
			<h3>CSC Mission and Goals<h3>

			<h4>Mission</h4>
			<p>The Department of Computing Sciences at Villanova University seeks to provide outstanding education, to advance scholarship, and to engage in activities that benefit society as a whole, in accordance to the University mission. The Department aims to equip students with a solid foundation in computing theory, and to prepare them for lifelong independent learning and innovative thinking in a constantly changing discipline. Its faculty members strive to maintain professional currency, and to involve students and colleagues in their research investigations. These endeavors support the University mission to transmit, pursue, and discover knowledge in an atmosphere of collegiality in the university community. Supported by a liberal arts education, the Department seeks to develop the total person, sensitive to social and ethical concerns impacted by the computing discipline, and committed to addressing the needs of a diverse modern society.</p>

			<h4>Mission Goals</h4>
			<p>These goals serve to solidify our vision. We will</p>

			<ol id="mission-list">
				<li>Continue to offer an accredited BSCS program, which successfully prepares its graduates for careers in industry, graduate education, and life-long learning.</li>
				<li>Maintain rigor and high standards in the MS programs, seeking to meet the needs of both part-time and full-time students.</li>
				<li>Advance our current program, create new programs, and promote interactions with other departments and programs to reflect the changing nature of computing.</li>
				<li>Introduce non-major students to the fundamental ideas of computer science and its social relevance.</li>
				<li>Maintain pedagogical excellence in teaching and advising.</li>
				<li>Ensure that all faculty members remain current in our rapidly changing discipline.</li>
				<li>Pursue theoretical and applied research to enhance the knowledge of computing, and involve undergraduate and graduate students in our research effort.</li>
				<li>Support the Department, the College, the University, the profession, and the local community through leadership and participation in committees, conferences, and organizations.</li>
				<li>Pursue inter-disciplinary projects in research and teaching.</li>
				<li>Strive to expand and diversify our faculty and enrollments.</li>
			</ol>
		</div>
    </div>

    </div>
</div>
			<div id="footer-wrapper"><!-- Footer Page to be used later -->
<footer>
	<link rel="stylesheet" type="text/css" href="/static/css/footer.css">
	<div class="footer">
		<h4><a href="http://www1.villanova.edu/main.html" style="color: white;">VILLANOVA UNIVERSITY</a></h4>
		<div class="footer">
			<p>Department of Computing Sciences</p>
			<a href="/aboutUs" style="color: white;">About Us | Contact Us</a>
			<p>Some rights reserved
                        <script type="text/javascript">document.write((new Date()).getFullYear());</script>
                        <noscript></noscript>
                        </p>
		<div>
	</div>
</footer></div>
		</div>
	</body>
</html>

# Close a File

In [10]:
f = open("testing.txt", "r")
print f.read()
f.close()

This a test!

How do you know if it passed?
You are reading everything currently in the file

Good Bye!